### PR TITLE
Writing etcd values only if the keys do not exist.

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by kovacshuni** [comment]
+1

**Comment by Zapadlo** [comment]
This is so annoying! I have a branch locally with absolute tonne of changes to achieve the same thing.

+1

**Comment by catalin-ilea** [comment]
Nice catch @Zapadlo . Updated.

**Comment by martingartonft** [comment]
lgtm.

**Comment by Zapadlo** [comment]
Merging, thanks @catalin-ilea

**Pull request merged**
