### PR TITLE
Set reboot strategy to off by default

### PR DESCRIPTION
**Pull request by tamas-molnar**

### CODE REVIEW

**Comment by tosan88** [comment]
:+1:

**Comment by khatton-ft** [comment]
:+1:

**Comment by Zapadlo** [comment]
From: https://coreos.com/os/docs/latest/update-strategies.html

```
#cloud-config
coreos:
  units:
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop
```

**Comment by tamas-molnar** [comment]
@Zapadlo Even better, thanks, added.

**Pull request merged**
