### PR TITLE
Remove DNS when decoming env

### PR DESCRIPTION
**Pull request by Zapadlo**

### CODE REVIEW

**Comment by martingartonft** [comment]
+1

**Comment by tosan88** [comment]
Might be worth to remove read DNS as well

**Comment by Zapadlo** [comment]
@tosan88 Yes, what sets that? I couldn't find it

**Comment by tosan88** [comment]
@Zapadlo: https://github.com/Financial-Times/up-service-files/blob/master/elb-dns-registrator.service#L13

**Comment by Zapadlo** [comment]
Ahhh, got it, will update, thanks!

**Comment by Zapadlo** [comment]
Updated.

**Comment by tosan88** [comment]
:+1:

**Pull request merged**
