### PR TITLE
Adding 3 bertha URLs to readme.

### PR DESCRIPTION
**Pull request by kovacshuni**

### CODE REVIEW

**Comment by catalin-ilea** [comment]
Do we expect to have different urls per environment/cluster? Otherwise you can configure those in the service files directly.

**Comment by martingartonft** [comment]
From recent discussions with some folks over here, people have wanted to re-point it via etcd to something else for testing.  So defaulting in provisioner to prod data, but override-able easily to something else. (I think i was talking with Sarah and Luca probably)

**Comment by kovacshuni** [comment]
A few weeks ago there was exactly an opposite PR on this: https://github.com/Financial-Times/coco-provisioner/pull/119 .
Can't find service files that would be using the roles and authors URLs directly either. They were removed from README, but not from provision.sh. Weird.

So we leave them in provisioner?

**Comment by izzyblues** [comment]
Yes. We have PROD and TEST spreadsheets. 
For Pre-prod and lower environments we are pointing to TEST spreadsheets.

**Comment by martingartonft** [comment]
Doing provisioner means we can change setup easily by environment manually in etcd, but also that we don't then have bertha urls public readable.

**Comment by kovacshuni** [comment]
This is not valid any more, Scott did some work after that included this as well.

**Pull request closed without merging**
