### PR TITLE
Varnish auth and protect etcd keys being reset

### PR DESCRIPTION
**Pull request by Zapadlo**
- removed: public_access_credentials + internal_access_credentials +
   vulcan_internal_authorization_header, replaced with varnish auth

 - bootstrap now checks if this is a first, otherwise does not run
   (should fix the issue where keys would get reset)

### CODE REVIEW

**Comment by Nesze** [comment]
+1

**Comment by catalin-ilea** [comment]
I'm confused, "etcdctl mk" is already supposed to fix the keys getting reset. Is there a scenario that I'm missing?

**Comment by Zapadlo** [comment]
Yep, primarily where keys get reset anyway.

We have observed now several times instances where the AWS keys have been reset to the previous values in userdata and last Friday `us` was running with `eu-west-1` region value (incorrect userdata that should've have been reset anyway).

There is no evidence to say these values get reset in userdata but at the same time there are not other services setting it.

@martingartonft ventured this can be caused following a restart where the box hasn't seen the cluster yet and updates it's own value. During the consensus that values becomes truth.

**Comment by catalin-ilea** [comment]
Ok, fair enough.
lgm

**Pull request merged**
