### PR TITLE
Allow udp port 123 out to allow timesync

### PR DESCRIPTION
**Pull request by Zapadlo**
Tested in pre-prod

### CODE REVIEW

**Comment by martingartonft** [comment]
Is it definitely 123 both from and to ports?

**Comment by Zapadlo** [comment]
No, thats just out. Why do we need in?

On 29 August 2015 17:02:59 BST, Martin Garton <notifications@github.com> wrote:
>Is it definitely 123 both from and to ports?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Financial-Times/coco-provisioner/pull/45#issuecomment-136005367

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martingartonft** [comment]
lgtm

**Comment by kovacshuni** [comment]
+1

**Pull request merged**
