### PR TITLE
Passing varnish credentials when provisioning. This allows having different passwords for different envs

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by BerniVarga** [comment]
+1

**Comment by Zapadlo** [comment]
Next and Mashery keys are in lastpass and expected to be passed in for prod ENVs? Could we have a lastpass link for when we need to restore prod in a hurry?

**Comment by Nesze** [comment]
lgtm

**Comment by catalin-ilea** [comment]
@Zapadlo Can't get a link to lastpass: hence the names of each lastpass credential so you can easily search for it. Hope it's good enough.

**Comment by Zapadlo** [comment]
Thats great, thanks!

**Comment by kovacshuni** [comment]
+1

**Pull request merged**
