### PR TITLE
Adding line for etcd cache-max-age

### PR DESCRIPTION
**Pull request by peteclark-ft**

### CODE REVIEW

**Comment by tamas-molnar** [comment]
LGTM 
Were the whitespace changes intentional?  Also, is this needed for the pub provisioner?

**Comment by peteclark-ft** [comment]
The whitespace changes weren't... Atom auto-formatting whitespace on save. Could that have an impact? 

As for the changes; the key is for globally configuring cache max-age in API responses - is that something the publishing cluster might need?

**Comment by khatton-ft** [comment]
I can't see any need for the publishing cluster to know that value.
Not sure whether the whitespace changes are significant or not. (The absence of a CRLF at the end of the file offends me but I can't say whether it's functional).

**Comment by tamas-molnar** [comment]
If there's no apps in the pub-cluster which use this key, it's not needed.
About the whitespace, it's yaml so it might affect things. But as long as you can create a new cluster with this branch it should be ok.

**Comment by peteclark-ft** [comment]
@tamas-molnar @khatton-ft - Tested this just now; cluster spun up fine, and the value was set. Let me know if you're happy for me to merge 👍

**Comment by tamas-molnar** [comment]
@peteclark-ft yeah, go ahead - please take into consideration the provisioner change process Sandor emailed yesterday.

**Pull request merged**
